language: node_js
node_js:
  - 9
  - 8
  - 7
  - 6

before_install:
  # - npm install -g npm # update to the latest npm to enable lock file usage
  - yarn global add greenkeeper-lockfile@1
  - yarn global add coveralls
before_script: greenkeeper-lockfile-update

cache:
  directories:
    - node_modules
script:
  - yarn test -- --coverage

# Only the node version 9 job will upload the lockfile and update coverage
after_script:
  - greenkeeper-lockfile-upload
  - test -f ./coverage/lcov.info && cat ./coverage/lcov.info | coveralls
